(ns site.themes
  "Theme system integration for ClojureScript DSL")

;; ============================================================================
;; Warm Color Palette (f.lux + Solarized + Daylight Computer inspired)
;; ============================================================================

(def sage-light-palette
  "Light sage theme inspired by warm, natural lighting"
  {:bg "#fefefe"
   :bg-secondary "#f8f9f7"
   :bg-tertiary "#f2f4f1"
   :text-primary "#2c3e2d"
   :text-secondary "#5a6c5b" 
   :text-muted "#8b9a8c"
   :primary "#4a7c59"
   :secondary "#6ba3a0"
   :accent "#f4a261"
   :border "#e6ebe7"})

(def jade-dark-palette
  "Dark jade theme with warm, f.lux-inspired tones"
  {:bg "#1a1d1b"
   :bg-secondary "#252b26"
   :bg-tertiary "#2f3530"
   :text-primary "#f4f0e8"
   :text-secondary "#e6ddd4"
   :text-muted "#b8aea5"
   :primary "#7fb069"
   :secondary "#5fb3b3"
   :accent "#ffa94d"
   :border "#3a4f3c"})

;; ============================================================================
;; Component Styling Generators
;; ============================================================================

(defn themed-component 
  "Wrap component with theme-aware styling"
  [component-hiccup theme-class]
  [:div {:class (str "themed-component " theme-class)}
   component-hiccup])

(defn farm-card
  "Generate a warm-themed farm information card"
  [title content & {:keys [theme accent-color]}]
  [:div {:class "farm-card"
         :style {:border-left (str "4px solid " (or accent-color "#4a7c59"))}}
   [:h3 {:class "card-title"} title]
   [:div {:class "card-content"} content]])

(defn metric-display
  "Display farm metrics with warm styling"
  [label value unit]
  [:div {:class "metric-display"}
   [:span {:class "metric-label"} label]
   [:span {:class "metric-value"} value]
   [:span {:class "metric-unit"} unit]])

(defn seasonal-info
  "Display seasonal farm information with appropriate theming"
  [season data]
  [:div {:class (str "seasonal-info season-" (name season))}
   [:h4 {:class "season-title"} (str "🍂 " (clojure.string/capitalize (name season)))]
   [:ul {:class "season-tasks"}
    (for [task data]
      [:li task])]])

;; ============================================================================
;; GitHub Pages Specific Components
;; ============================================================================

(defn github-pages-nav
  "Navigation component optimized for GitHub Pages routing"
  [sitemap current-page lang]
  [:nav {:class "github-pages-nav"}
   [:div {:class "nav-container"}
    [:a {:href (str "/" lang "/") :class "home-link"} 
     "🌽 NixtaVeganic"]
    [:div {:class "nav-links"}
     (for [item sitemap]
       [:a {:href (str "/" lang "/wiki/" (:id item))
            :class (str "nav-link" (when (= current-page (:id item)) " active"))}
        (:title item)])]]])

(defn i18n-page-wrapper
  "Wrap page content with internationalization support"
  [content lang alternate-langs]
  [:div {:class "i18n-page-wrapper" :lang lang}
   [:div {:class "language-alternatives"}
    "Also available in: "
    (for [alt-lang alternate-langs]
      [:a {:href (str "/" alt-lang "/") :class "alt-lang-link"}
       (case alt-lang
         "en" "English 🇺🇸"
         "es" "Español 🇪🇸"
         alt-lang)])]
   [:main {:class "page-content"}
    content]])

;; ============================================================================
;; Theme-Aware CSS Generation
;; ============================================================================

(defn generate-themed-css
  "Generate CSS with warm color variables"
  []
  (str 
    "/* Warm theme CSS generated by ClojureScript DSL */\n"
    ":root {\n"
    (clojure.string/join "\n"
      (for [[key value] sage-light-palette]
        (str "  --sage-" (name key) ": " value ";")))
    "\n}\n\n"
    ".theme-dark {\n"
    (clojure.string/join "\n" 
      (for [[key value] jade-dark-palette]
        (str "  --jade-" (name key) ": " value ";")))
    "\n}\n\n"
    "/* Farm-specific component styles */\n"
    ".farm-card {\n"
    "  background: var(--sage-bg-secondary);\n"
    "  border-radius: 12px;\n"
    "  padding: 1.5rem;\n"
    "  margin: 1rem 0;\n"
    "  box-shadow: 0 4px 12px rgba(74, 124, 89, 0.1);\n"
    "  transition: all 0.3s ease;\n"
    "}\n\n"
    ".theme-dark .farm-card {\n"
    "  background: var(--jade-bg-secondary);\n"
    "  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);\n"
    "}\n"))

;; ============================================================================
;; Export functions for main DSL
;; ============================================================================

(def theme-exports
  {:themed-component themed-component
   :farm-card farm-card
   :metric-display metric-display
   :seasonal-info seasonal-info
   :github-pages-nav github-pages-nav
   :i18n-page-wrapper i18n-page-wrapper
   :generate-themed-css generate-themed-css
   :sage-light-palette sage-light-palette
   :jade-dark-palette jade-dark-palette})

